package com.web;


import java.util.Date;

/**
 * @author JonathanCauchi
 *
 * This class holds the ticket details generated by the system and displayed to the user
 */
public class Ticket 
{
	private int ticketNumber;
	private int slotNumber;
	private long startTime;
	private long endTime;
	private String slotPosition;
	private double totalFee;
	
	
	public Ticket() {

	}
	
	public Ticket(int ticketNumber, int slotNumber, long startTime, long endTime, String slotPosition,
			double totalFee) {
		super();
		this.ticketNumber = ticketNumber;
		this.slotNumber = slotNumber;
		this.startTime = startTime;
		this.endTime = endTime;
		this.slotPosition = slotPosition;
		this.totalFee = totalFee;
	}

	public double getTotalFee() {
		return totalFee;
	}

	public void setTotalFee(double totalFee) {
		this.totalFee = totalFee;
	}

	public int getTicketNumber() {
		return ticketNumber;
	}
	public void setTicketNumber(int ticketNumber) {
		this.ticketNumber = ticketNumber;
	}
	public int getSlotNumber() {
		return slotNumber;
	}
	public void setSlotNumber(int slotNumber) {
		this.slotNumber = slotNumber;
	}
	public long getStartTime() {
		return startTime;
	}
	public void setStartTime(long startTime) {
		this.startTime = startTime;
	}
	public long getEndTime() {
		return endTime;
	}
	public void setEndTime(long endTime) {
		this.endTime = endTime;
	}
	public String getSlotPosition() {
		return slotPosition;
	}
	public void setSlotPosition(String slotPosition) {
		this.slotPosition = slotPosition;
	}
	
	
	
	
}
